version: '3.4'

services:
  netflixgpt:
    image: netflixgpt
    build:
      context: netflix-GPT
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3005:3005
